/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.com.caixavidaeprevidencia.desafio.caixa.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import br.com.caixavidaeprevidencia.desafio.caixa.dtos.ProdutoDTO;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2025-02-24T14:25:40.604593500-03:00[America/Sao_Paulo]")
@Api(value = "ProdutoController", description = "the ProdutoController API")
public interface ProdutoControllerApi {

    @ApiOperation(value = "", nickname = "getProdutoById", notes = "", response = ProdutoDTO.class, tags={ "produto-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProdutoDTO.class) })
    @RequestMapping(value = "/api/produtos/{idProduto}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<ProdutoDTO> getProdutoById(@ApiParam(value = "",required=true) @PathVariable("idProduto") Long idProduto);

}
